### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by carlo-github** [OCA/currency#60]
HTTP Error 403: Forbidden odoo12
when perform action "Update Rates Wizard" in     Currency Rates Providers/OpenExchangeRates.org
currency EUR RON

ihave put de app id in configuration

![Firefox_Screenshot_2019-07-06T13-43-28 056Z](https://user-images.githubusercontent.com/36795969/60757035-8b11f000-a005-11e9-99c6-c49c53451916.png)
![Firefox_Screenshot_2019-07-06T13-44-04 885Z](https://user-images.githubusercontent.com/36795969/60757036-8b11f000-a005-11e9-80fe-7a504fea4930.png)
![Firefox_Screenshot_2019-07-06T13-44-41 905Z](https://user-images.githubusercontent.com/36795969/60757037-8b11f000-a005-11e9-92fe-a66b1546e492.png)

**Comment by gaikaz** [comment]
Getting same error. After investigation, the problem seems to be rising from incorrect authorization header being sent to OXR API.

Suspected line of code:
https://github.com/OCA/currency/blob/12.0/currency_rate_update_oxr/models/res_currency_rate_provider_OXR.py#L106

On this line, the header is set like so:
`'Bearer %s' % self.company_id.openexchangerates_app_id`
Which simplified would be:
`'Bearer YOUR_APP_ID'`
Which by urllib is most likely being parsed to:
`"Authorization: Bearer YOUR_APP_ID"`

According to OXR API documentation, correct header would be:
`"Authorization: Token YOUR_APP_ID"`

OXR API documentation state:

> **Please note:** The format of the HTTP header must be exactly as above ...

Documentation reference:
https://docs.openexchangerates.org/docs/authentication#http-header-authentication

I also tested this with Postman, which confirms, that OXR returns `403` if called with authorization header with keyword `Bearer` and gives correct response with keyword `Token`.

**Comment by carlo-github** [comment]
> Getting same error. After investigation, the problem seems to be rising from incorrect authorization header being sent to OXR API.
> 
> Suspected line of code:
> https://github.com/OCA/currency/blob/12.0/currency_rate_update_oxr/models/res_currency_rate_provider_OXR.py#L106
> 
> On this line, the header is set like so:
> `'Bearer %s' % self.company_id.openexchangerates_app_id`
> Which simplified would be:
> `'Bearer YOUR_APP_ID'`
> Which by urllib is most likely being parsed to:
> `"Authorization: Bearer YOUR_APP_ID"`
> 
> According to OXR API documentation, correct header would be:
> `"Authorization: Token YOUR_APP_ID"`
> 
> OXR API documentation state:
> 
> > **Please note:** The format of the HTTP header must be exactly as above ...
> 
> Documentation reference:
> https://docs.openexchangerates.org/docs/authentication#http-header-authentication
> 
> I also tested this with Postman, which confirms, that OXR returns `403` if called with authorization header with keyword `Bearer` and gives correct response with keyword `Token`.

Thank you for your reply.. I modified that line, upgraded the module from Odoo and even restart it.. but unluckly I obtain again the same error 403.. and from Odoo log any other information against
"2019-08-05 14:06:02,397 5933 WARNING LVN001 odoo.addons.currency_rate_update.models.res_currency_rate_provider: Currency Rate Provider Failure: HTTP Error 403: Forbidden "
Any other suggest?

**Comment by gaikaz** [comment]
@carlo-github
Sorry, forgot to mention that I tried to change that myself with no success. I can only guess now, that urllib does something more with request headers under the hood, that we are not aware of.

_Just thoughts, but it would be great if this module used `requests` library instead of `urllib`. Would probably make it much easier to debug now._

**Comment by carlo-github** [comment]
> @carlo-github
> Sorry, forgot to mention that I tried to change that myself with no success. I can only guess now, that urllib does something more with request headers under the hood, that we are not aware of.
> 
> _Just thoughts, but it would be great if this module used `requests` library instead of `urllib`. Would probably make it much easier to debug now._

So this is a bug or? what need to do?

**Comment by gaikaz** [comment]
It is a bug. We need someone with time, skill and resources to fix this. 

@alexey-pelykh , you seem to be the main contributor of this module and very active here in general. What are your thoughts on this? Could you point us in the right direction?

**Comment by alexey-pelykh** [comment]
@gaikaz just tested on Postman:
1. Without `app_id` in needed we need to specify `Token` instead of `Bearer`. So a PR fixing that would be welcomed.
2. With `app_id` it ignores header completely, so we're ok even without that.

@carlo-github you've mentioned that you're using EUR<>RON currency pair. I assume that you're having paid plan?

**Comment by carlo-github** [comment]
> @gaikaz just tested on Postman:
> 
> 1. Without `app_id` in needed we need to specify `Token` instead of `Bearer`. So a PR fixing that would be welcomed.
> 2. With `app_id` it ignores header completely, so we're ok even without that.
> 
> @carlo-github you've mentioned that you're using EUR<>RON currency pair. I assume that you're having paid plan?

Thank you.. as per their website
"Our popular Free Plan provides hourly updates (with base currency USD) and up to 1,000 requests/month."
So I'm using the free plan because my update should be 1 time per day.

**Comment by alexey-pelykh** [comment]
@carlo-github *(with base currency **USD**)*,: it your case your free plan does not allow EUR as base currency

In other words, it's not a bug and issue you're seeing is valid - you don't have permission to get EUR<>RON rates

**Comment by pedrobaeza** [comment]
wrong ping. It should be @carlo-github

**Comment by alexey-pelykh** [comment]
Oh, sorry. My bad, multitasking

**Comment by carlo-github** [comment]
> @carlo-github _(with base currency **USD**)_,: it your case your free plan does not allow EUR as base currency
> 
> In other words, it's not a bug and issue you're seeing is valid - you don't have permission to get EUR<>RON rates

You are right.. I had create a new db with USD as main currency and the service working well for the rates against EUR.
As I have actually some database with EUR ans some other with RON as main currency, what do you suggest for sort out this problem? Are there other service for update the rates daily?
Thank you.

**Comment by alexey-pelykh** [comment]
@carlo-github if you're looking for free one, probably ECB is a choice for you? Also https://github.com/OCA/currency/pull/52 may work out for you

**Comment by alexey-pelykh** [comment]
@pedrobaeza this issue may be closed I think

**Comment by pedrobaeza** [comment]
Yes. @carlo-github be thankful to @alexey-pelykh that has given you free extra support outside the scope of the issue tracker.
